### ISSUE TITLE
CoreSync Usage

### ISSUE THREAD

**Issue by Orgbrat** [adospace/CoreSync#1]
So I want to sync two sqlite databases, one will reside on device ( client ) and one will reside in OneDrive or DropBox.  Have you some usage instructions on how to do this with your library?

**Comment by adospace** [comment]
Did you look at tests? CoreSync/src/CoreSync.Tests/IntegrationTests.cs contains a couple of tests of synchronization between 2 SQLite databases

**Comment by Orgbrat** [comment]
Couple of further questions please..

1. Is it correct that the EntityFramework is not required as only the Tests project is using it?
    Am currently using the SQLite-net library [](https://github.com/praeclarum/sqlite-net) in a new 
    Xamarin application and would like to continue using this library for SQLite access.
2. Is the Created or Updated columns in the tables required for proper synchronization in each table?
3. What is the difference between Test1_Sqlite_Sqlite and Test2_Sqlite_Sqlite for SQLite to SQLite synchronization.

Orgbrat

**Comment by adospace** [comment]
1. Yes, it's correct, EF is not required at all: I just used it in tests for convenience as I was not obligated to deal with specific SQL language dialect in each test. Using EF was also an easy choice as I wanted to abstract away from specific database implementations etc.
2. I assume you refer to Created/Update columns in Users or Posts table: no they are not required, are just dummy columns I've added to that entities/tables.
3. Test2 is just a more complicated example of insert/update/delete operations. Test1 is easier to follow at first approach.

**Comment by adospace** [comment]
@Onotseike sorry but I need more context to understand your question, column type varchar(x) seems a SQL Server type while the code refers to Sqlite?

**Comment by Onotseike** [comment]
Hey @adospace ,
That is fine. The library the original poster mention [https://github.com/praeclarum/sqlite-net](sqlite-net) treats Guid  as varchar(36) see[https://github.com/praeclarum/sqlite-net/wiki/Features#features](ORM) and the result of this means when creating the sqlite database and tables with the library mentioned above, a primary key with datatype Guid will result in a varchar (36)
![image](https://github.com/adospace/CoreSync/assets/5883457/92730b08-86aa-4324-9fe6-b49b39948b1a)
